# Generated by Django 4.0.6 on 2022-07-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='average',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
